### ISSUE TITLE
Asking some aprovments in Homework week3.

### ISSUE THREAD

**Issue by Meno-101** [HackYourFuture/React#359]
Looking to the results of students class18'th homeworks and their hard work, I found it's very useful to have multiple programs into one application.
showing them how we could make multiple programs related to each other with nothing but the parent Component providing for them a great experience with the Feature Synonyms, and what they may find of a strange requirements from their clients in the job market.

The second and third steps for me were a great steps forward into their journey with the `life cycle hooks` and the server side integration, By looking to what do we have:
 - The very first one is for learning how to deal with a third party API.
 - after words we have
> Create reusable components, at least 3

I kindly disagree on this part before I saw the homeworks, supported with results of what we do have in the homeworks afterwards:
 - #358 ( 2 ) components.
 - #357 ( 1 ) component.
 - #356 ( 3 ) components with a little bit of content 👌🏻.
 - #355 ( 3 ) 🙌.
 - #354 ( 2 ) for being accurate.
 - #353 ( ... ) we can't say they are three but also they are three, in another side of view they are 3. _(one contains two)_

And we have the great addition we hadn't before which is (Development server).
It's Great, well organized, and having a very nice steps which includes:
 - (1) loading in of Express and initializing it
 - (2) code that let's Express know where you hold your static files
 - (3) a GET route that sends the index.html file from your public folder in the client as a response to the browser (take the / route)
 - (4) a listener to a random PORT number (for example, 1234)
 - (5) inside the package.json of write a rule for a proxy that refers the React development server to the Express server port

My comments:
 - (1) 🙌
 - (2) we can't say all done _(from small discussion I knew it's because of what to serve and why)_
 - (3) exactly as it's previous. _(Also same with the routes)_
 - (4) 🙌
 - (5) 🙌

But the most important parts are not clear yet. my guess here is because there is no goal nor a connection of these multiple applications. (back-end front-end)

what I may suggest instead we could have a small feature on the front-end connected with it's end point on a back-end as a student made also we can provide the third party application feature front or back so it's a win win, And we can keep the last homework submission component as a feature asking to fix and shortness long codes from their new experience of the current week, as any company employments.

**Comment by eneserdek** [comment]
Installing react application to be avaliable to use it offline takes some time. And we are doing it whilst class. However that can be done before coming to class. So, I offer adding the following lines to the begining of the React Week 3 readme part.

-----
It is recommended for students to install react application before coming to class. Please follow the steps below to install react app in order to use it offline.

1. Open terminal and enter the following lines 
npm install -g create-react-app 
*linux and mac users may add sudo to the beginning of the command.
*This command installs the required files to install react, react dom, react-scripts.

2. Write down following lines to the terminal 
npm init react-app my-app 
*This will creates a folder with the name my-app inside the current folder and installs required react modules.

**Comment by NoerGitKat** [comment]
Thanks for the comments everyone! The module has been updated a month ago and I hope it has resolved some of these issues mentioned. If not, please make another issue :)
